spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/room_booker
    username: paul
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true